### ISSUE TITLE
Deploy lattice status dashboard with lattice

### ISSUE THREAD

**Issue by BenElgar** [mlab-lattice/system__status-dashboard#1]

**Comment by BenElgar** [comment]
Made some progress with this but hit a couple of roadblocks with a 500 and a 403 out of lattice

**Comment by BenElgar** [comment]
Fixed a couple of (pretty stupid) mistakes I made which solved a couple of the issues I was facing but then I ran into another with setting secrets where lattice is returning a 500 with the following error: `Unrecognized first argument: undefined`.

**Comment by BenElgar** [comment]
Getting through a few secret related issues with @kevindrosendahl's assistance.

**Comment by BenElgar** [comment]
Successfully builds now but can't seem to deploy.

**Comment by BenElgar** [comment]
Currently bashing my ahead against a wall trying to fix an environmental issue within the container that I can't replicate locally

**Comment by willshulman** [comment]
Maybe slack Kevin or the larger group

**Comment by BenElgar** [comment]
It works! 🎉

Need to set up an appropriate DNS name and merge in the UI stuff but I should have something to show tomorrow.

**Comment by BenElgar** [comment]
It wasn't quite as working as it first appeared but I think it is now. Gave it an appropriate DNS name: http://internal-status.lattice.mlab.com/. No HTTPS yet seeing as SSL load balancers aren't supported yet. Waiting on creds to be added to the vault.

**Comment by BenElgar** [comment]
Creds are in the shared vault.

**Comment by BenElgar** [comment]
I'm actually going to call this done.
